import { Person } from '../models/person';

export const people: Person[] = [
    { id: 1, handle: 'Abhishek', name: 'Abhishek Bhombore', company: 'Microsoft', position: 'Senior Software Engineer, Azure', rating: 5.0, reviews: 3, details: "Abhishek is a Senior Software Engineer working on AI experiences for the Azure Portal. Perviously, he worked on building and scaling Infra-as-a-Service offerings on Azure, including Azure virtual machines, Azure Kubernetes Service, and more. Talk to him about building 0 to 1 products, get his input on your resume, and more.", image: '/images/people/Abhishek.png' },
    { id: 2, handle: 'Rodrigo', name: 'Rodrigo Canaan', company: 'University', position: 'Assistant Professor of Computer Science (Cal Poly)', rating: 5.0, details: "Researcher of Artificial Intelligence and Games at NYU. Developing AI that can model human players and adapt during cooperative gameplay, using Evolutionary Computation, Reinforcement Learning and Bayesian Inference. Co-organizer of the Generative Design in Minecraft Competition (GDMC).", reviews: 4, image: '/images/people/Rodrigo.png' },
    { id: 3, handle: 'Michael', name: 'Michael Green', company: 'University', position: 'PhD in AI & Adjunct @ NYU Tandon', rating: 5.0, reviews: 5, image: '/images/people/Michael.png' },
    // { id: 4, handle: 'Claire', name: 'Claire Goetschel', company: 'Microsoft', position: 'Senior UX Designer', rating: 5.0, reviews: 7, image: '/images/people/Claire.png' },
    // { id: 5, handle: 'Bryan', name: 'Bryan Oubaita', company: 'Amazon', position: 'Engagement Security Leader, AWS', rating: 5.0, reviews: 4, image: '/images/people/Bryan.png' },
    { id: 6, handle: 'Abhay', name: 'Abhay Sawney', company: 'Microsoft', position: 'Product Manager, Azure Portal', rating: 5.0, reviews: 40, image: '/images/people/Abhay.png' },
    // { id: 7, handle: 'M', name: 'M Charity', company: 'University', position: 'Assistant Professor of AI (University of Richmond)', rating: 5.0, reviews: 45, image: '/images/people/M.png' },
    { id: 8, handle: 'Aimee', name: 'Aimee Wu', company: 'Microsoft', position: 'UX Designer, Azure IaaS', rating: 5.0, reviews: 5, image: '/images/people/Aimee.png' },
    { id: 9, handle: 'Munad', name: 'Munad Mahinoor', company: 'PayPal', position: 'Engineering Manager', rating: 5.0, reviews: 0, image: '/images/people/Munad.png' },
    { id: 10, handle: 'Sam', name: 'Sam Fernandez', company: 'Microsoft', position: 'Product Manager, Azure', rating: 5.0, details: "As a Product Manager at Microsoft, I specialize in generative AI and front-end UX for Azure Kubernetes Service (AKS) and Virtual Machines. I lead cross-functional teams to deliver enterprise-requested features that enhance user engagement and efficiency. My expertise in UX design methods, including customer interviews, usability testing, Figma prototyping, and A/B testing, has led to significant improvements in user satisfaction and Net Promoter Scores across Azure. \n \n Before joining Microsoft, I honed my skills at The Walt Disney Company and American Express, where I led quality assurance and UI design projects, streamlining processes and advocating for accessibility. I am dedicated to serving customers, leveraging user feedback and data analysis to continually optimize the user experience and ensure product-market fit. My extensive background in the technology industry highlights my commitment to delivering top-notch products and driving customer success. \n \n Outside of work, I love Pilates, Zumba, rock concerts, glitch art, the Fallout and Witcher video game series, and Linkin Park!", reviews: 0, image: '/images/people/Sam.png' },
    { id: 11, handle: "Adrian", name: 'Adrian Perez', company: 'Microsoft', position: 'Software Engineer II, XBOX', rating: 5.0, reviews: 0, details: "Second generation, Cuban-American software engineer passionate about enriching the lives of others through meaningful system design. From the very beginning of my computer science and mathematics journey, I have regarded artificial intelligence as the prime way of impacting people; enabling any person or group to engage in spaces once thought to be out of reach. This shows through my current work at Xbox as well as prior research in natural language processing, AI for weather systems, underwater robotics. \n \n I received my B.S. in Computer Science and B.S. in Mathematics from Florida International University (FIU). At FIU I engaged in active research for AI across several fields: meterology, NLP, and robotics. I also was heavily engaged in the hackathon community where I bridged the gap between research and production in short-time frames. I am proud to say that I was also heavily involved with the INIT organization as a student leader and contributor.", image: '/images/people/Adrian.png' },
    // { id: 12, name: 'Mia Green', company: 'Amazon', position: 'L4 Product Manager, Amazon Web Services', rating: 4.8, reviews: 45, image: '/images/people/2.png' },
    // { id: 13, name: 'Noah Blue', company: 'University', position: 'L6 Research Scientist, Stanford University', rating: 4.9, reviews: 50, image: '/images/people/3.png' },
    // { id: 14, name: 'Olivia Yellow', company: 'PayPal', position: 'L5 Software Engineer, PayPal', rating: 4.7, reviews: 40, image: '/images/people/4.png' },
    // { id: 15, name: 'Paul Purple', company: 'NVIDIA', position: 'L3 Graphics Engineer, NVIDIA', rating: 4.9, reviews: 55, image: '/images/people/5.png' },
    // { id: 16, name: 'Quinn Red', company: 'Capital One', position: 'L5 Data Scientist, Capital One', rating: 4.6, reviews: 35, image: '/images/people/1.png' }
];
